# Generated by Django 5.2.5 on 2025-08-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicerequest_description_user_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('gardening', 'Gardening'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning'), ('painting', 'Painting'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
