# Generated by Django 5.2.5 on 2025-08-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='aboutus',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=15),
        ),
    ]
